---
homebrew_taps:
  - caskroom/cask

homebrew_package_removals:
  # - python3  # Replaced with python34 for the time being

homebrew_packages:
  - autoconf
  - autojump
  - automake
  - bazaar
  - coreutils
  - codemod
  - cowsay
  - docker
  - docker-compose
  - editorconfig
  - exiftool
  - ffmpeg
  - freetype
  - fswatch
  - gdbm
  - ghostscript
  - git
  - gitg
  - gpg
  - heroku
  - hub
  - imagemagick
  - jpeg
  - jpegoptim
  - jq
  - lesspipe
  - libevent
  - libffi
  - libmemcached
  - libpng
  - libtool
  - libyaml
  - md5sha1sum
  - memcached
  - mercurial
  - ncdu
  - node
  - nvm
  - openssl
  - ossp-uuid
  - pandoc
  - percona-toolkit
  - pkg-config
  - pngcrush
  - postgres
  - pyenv
  - pypy
  - python
  - python3
  - readline
  - redis
  - rtmpdump
  - ruby
  - ruby-build
  - ruby-install
  - shellcheck
  - sloccount
  - sqlite
  - tree
  - tig
  - watch
  - wget
  - xhyve
  - xz
  - zsh-completions

homebrew_cask_packages:
  - emacs
  - flux
#  - google-chrome
#  - google-drive
#  - iterm2
#  - psequel
  - reggy
  - rescuetime
#  - sequel-pro
#  - skype
#  - slack
#  - spotify
  - vagrant
  - virtualbox
  - vlc

pip_packages:
  - autopep8
  - awscli
  - awslogs
  - boto
  - boto3
  - csvkit
  - flake8
  - httpie
  - importmagic
  - ipdb
  - ipython
  - jedi
  - lifelogger
  - pep8
  - pillow
  - pygments
  - pylint
  - pythonpy
  - pyyaml
  - requests
  - restructuredtext_lint
  - rope
  - sh
  - six
  - tldr
  - virtualenvwrapper
  - yamllint

npm_packages:
  - jsxhint
  - gulp
  - bower

gem_packages:
  - i18n
  - jekyll
  - jekyll-gist
  - jekyll-paginate
  - jekyll-tagging
  - pygments.rb
  - redcarpet
  - travis
