---
homebrew_taps:
  - caskroom/cask

homebrew_package_removals:
  - python3  # Replaced with python34 for the time being

homebrew_packages:
  - autoconf
  - autojump
  - automake
  - bazaar
  - brew-cask
  - coreutils
  - cowsay
  - editorconfig
  - exiftool
  - ffmpeg
  - freetype
  - fswatch
  - gdbm
  - git
  - gpg
  - hub
  - imagemagick
  - jpeg
  - jpegoptim
  - jq
  - lesspipe
  - libevent
  - libmemcached
  - libpng
  - libtool
  - libyaml
  - md5sha1sum
  - memcached
  - ncdu
  - node
  - openssl
  - ossp-uuid
  - percona-toolkit
  - pkg-config
  - pngcrush
  - pypy
  - python
#  - python34
  - readline
  - rtmpdump
  - ruby
  - ruby-build
  - ruby-install
  - shellcheck
  - sloccount
  - sqlite
  - tree
  - tig
  - watch
  - wget
  - xz
  - zsh-completions

homebrew_cask_packages:
  - emacs
  - flux
  - pgadmin3
  - sequel-pro
  - skype
  - spotify
  - vagrant
  - virtualbox

pip_packages:
  - csvkit
  - flake8
  - ipdb
  - ipython
  - pep8
  - pygments
  - pylint
  - pythonpy
  - pyyaml
  - requests
  - sh
  - six
  - tldr
  - virtualenvwrapper
  - restructuredtext_lint

npm_packages:
  - ember-cli

gem_packages:
  - jekyll
  - jekyll-tagging
